### PR TITLE
Naive update tf to net5

### PR DESCRIPTION
**Pull request by tebeco**
As said, this is a very super naive update to `net5.0`
Especially in the very short term to have transitive resolving `Msft.Anc.xxxx` in 5.0.x rather than 3.1.x

I see you also have a branch ongoing during `5.0-preview`, but not sure if I should attempt to rebase that other branch, or anything else already on the way

### CODE REVIEW

**Comment by davidfowl** [comment]
This shouldn't require .NET 5.

**Comment by tebeco** [comment]
I don't think it "require" it, I confirm.

When i toyed with bedrock i was trying to understand why nugets in the VS dependency tree we could spot 3.x dependencies
I can't remember exactly if it was because of a transitive begin resolved in one way (older) or in fact to 5.0 (Bcl included, eg: `System.Io.Pipeline` is pinned to 4.7.x)

And I think at the end I was just like "why not attempt"
Feel free to dismiss this PR or I could attempt cross targeting both  (using same "naive code change") with few `Condition` to resolve updated packages if you want

no feeling on this one :D

**Comment by tebeco** [comment]
closing I guess :D ?

**Comment by jzabroski** [comment]
> why nugets in the VS dependency tree we could spot 3.x dependencies
> 
> -- @tebeco 

I think Andrew Lock's blog post may be of help to you.  In particular, this image is awesome: 
image

**Comment by jzabroski** [comment]
The other thing that can be confusing is that a lot of the VS dependency tree relies on the `obj` directory as a cache of these dependencies.  So, if you convert from one target framework to another, VS will get confused.  For this reason, I usually close Visual Studio and run a CleanFull target I created to address this problem. See: https://github.com/dotnet/sdk/issues/3067 - I proposed this be added to the SDK but after some discussion, we decided `git reset --hard HEAD` was simpler and more fool-proof, even if it requires using your VCS to do the operation.

**Comment by tebeco** [comment]
Thanks you for taking some time to redact these suggestions

The PR was about pulling aspnetcore 3.1 transitively (`FrameworkReference` is driven by the `Sdk`), in an application using `Sdk 5.0`)
So this implies possible (breaking ?) changes if your application is `net5.0` but library you use are built targeting `netcoreapp3.1`
=> Changing `global.json` would not "fix" a breaking change if both side are not compliant (eg: if bedrock used an API specific to 3.1 that had a breaking change in 5.0) 
But as noted, It's does not look necessary so the PR was closed for that reason.

Regarding the trouble and confusion of VS and `obj` folder, I would rather not recommend `git reset --hard`
If you're going for cleaning your local `git` repository then I'd rather suggest 
* `git clean -fdx` to avoid possible loss of tracked file you were currently working. (There's a command for `git clean` rather than `reset`)
* `dotnet restore --force`
* disabling Visual Studio to run background restore will not "get VS confused"
* And if you still doubt yourself on that, just close VS before you do that all
Every one have it own way, works like a charm, thanks you for the suggestion.

`git clean -h`:
```
>     -f, --force           force
>     -d                    remove whole directories
>     -x                    remove ignored files, too
> ```
> so this will remove all untracked file and then empty folder, assuming you properly setup `.gitignore` and never did a `git add` on a file inside `obj` or `bin` (the `-x`) then it will also delete these folder with `-d`
> 
> `dotnet restore --help`:
> ```
>   -f, --force                          Force all dependencies to be resolved even if the last restore was successful.
>                                        This is equivalent to deleting project.assets.json.
> ```
> Note: you can also find switch like `--no-cache` if you don't trust your local HTTP cache
> And if you are pushy you can even have fun with `dotnet nuget locals --clear all` to drop the nupkg global cache folder (like when you have corrupted HASH on `locked-mode`)

**Comment by jzabroski** [comment]
> eg: if bedrock used an API specific to 3.1 that had a breaking change in 5.0, and your application is running AspNetCore 5

While all of that may be true, that doesn't explain why you saw 3.1 dependencies in your Visual Studio Solution Explorer, under a `*.csproj` Dependencies. 

> * disabling Visual Studio to run background restore will not "get VS confused"

I didn't understand.  What Visual Studio setting is that?  Nuget Package Manager Settings doesn't have this option in my version of VS2019.

> Changing `global.json` locally would not affect the transitivity of the library

Changing global.json won't, but changing `<RollForward>LatestMajor</RollForward>` will cause your FrameworkReference values to point to the latest framework libraries.  The default is LatestMinor.  It arguably should have been LatestFeature, especially given the odd decision to not provide [long-term support](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) for .NET Core 2.2 but instead provided it for .NET Core 2.1 (but roll forward was introduced after this weird situation, so it's a moot point).  It's really a matter of where you put the toggle as to whether it will work or not.  The point is that it would be illogical to compile an app that is meant to target the LatestWhatever from your local development environment, and then have that be different from what would actually get run if you immediately debugged it and linked-and-loaded the deps at run-time.

There are some edge cases where RollForward itself is insufficient, like adding assemblies to your current AssemblyLoadContext, but that is because the .NET Core machinery doesn't apply to run-time dependency management.  However, that would not explain why your VS got messed up.

**Comment by tebeco** [comment]
Again, thx for the time taken here.

I have nothing more to add to the title of the PR for a toy project ;)

**Comment by jzabroski** [comment]
> Regarding VS, the screen changed but I think these are the settings:

I think they may have removed that option, because the main reason it existed is the Visual Studio event model was absolute insanity and would fire a thousand package restore events, and all plug-ins would try to respond to those events but had no concept of when _all_ nuget package references were restored.  That is why I mentioned that you might need to close and re-start Visual Studio, as the background MSBuild.exe (32-bit) and VBCSCompiler binaries might be hung.  In particular, `DotNetCompilerPlatformTasks.dll` can be locked by a .NET Framework process, which can happen if your solution has any legacy .NET Framework csproj files.

**Comment by jzabroski** [comment]
Basically, if you want to get to the root, root cause of why you got a particular dependency version, use MSBuildStructuredLogViewer tool, and find Add Item Reference and Remove Item Reference nodes in the MSBuild binlog output.  It is sometimes necessary to also inspect the dll pointed to by the MSBuild binlog output, using a decompiler tool like JetBrains dotPeek.

**Comment by tebeco** [comment]
feel free to do so if you think that would help you ;)

I'm now unsubscribing from this since most discussion is of topic and the PR was closed

have a good day

**Pull request closed without merging**
