### PR TITLE
wireshark style logging

### PR DESCRIPTION
**Pull request by AndyPook**
allows different formatting of Logging middleware.
Provider formatter for WireShark style.

Have made the formattter configurable. But could just replace the existing `Log` method is you want to keep this simple

### CODE REVIEW

**Comment by halter73** [comment]
So this outputs something similar to Wireshark's [Packet Bytes Pane](https://www.wireshark.org/docs/wsug_html_chunked/ChUsePacketBytesPaneSection.html)? Cool stuff!

We've also [talked about trying to generate a pcap file](https://github.com/dotnet/aspnetcore/issues/12099) which would be ingestible by Wireshark. It wouldn't be possible to know packet boundaries, packet headers, etc., but it might be possible to fake some of that. It could be useful for taking advantages of some features of Wireshark like it's [HTTP/2 dissector](https://wiki.wireshark.org/HTTP2).

**Comment by davidfowl** [comment]
@AndyPook Got a screenshot consuming this format?

**Comment by AndyPook** [comment]
> @AndyPook Got a screenshot consuming this format?

image

**Comment by davidfowl** [comment]
Dude, this should just be the default.

**Comment by davidfowl** [comment]
I'm going to merge this and then flip the default.

**Comment by shaggygi** [comment]
@jefffhaynes while I don't know the specifics where this feature (along with [this one](https://github.com/dotnet/aspnetcore/issues/12099)) is headed, but it might be helpful chiming in with some of your good experience/work on [PcapNgNet](https://github.com/jefffhaynes/PcapNgNet).  Thoughts?

**Pull request merged**
