### PR TITLE
DocFX generated API docs

### LINKED ISSUE #45: Generate API docs site using docfx
We'll need an API docs for this project and docfx is the new hotness. We should figure out how to set that up.

### PR DESCRIPTION
**Pull request by damieng**
Nice project!

This fixes #45 but before merging should decide if you want to either:

1. Have the site generated in a `gh-pages` branch to keep noise down on `master`
2. Have the docs generated and served out of a `/docs` folder?
3. Serve the site out of somewhere else

I can then make the necessary changes to this config (and revert the .gitignores)

To try this out for yourself you'll need to:

1. Install docfx
2. Go into the `docs` folder and run `docfx --serve`
3. Open your browser to `http://localhost:8080`

Here's how it looks (default theme):

image

### CODE REVIEW

**Comment by davidfowl** [comment]
@damieng Thanks for the PR. I need to figure out the hosting. What would be the best way to do keep the running site so we can keep looking at it as we make change? Github pages?

**Comment by damieng** [comment]
GitHub pages is super-simple to set-up.  Easiest would be to have to docs auto-build using CI (or perhaps GH action) into gh-pages branch.

**Comment by jkotalik** [comment]
I'm in favor of having this in Github pages as well. @damieng how much noise is created by DocFX docs? I'd prefer not to have a separate branch if possible.

**Comment by damieng** [comment]
GitHub pages requires all the statically generated docs exist in the repo.  So that's quite a lot of noise as it generates and updates them.

**Comment by damieng** [comment]
Do you want to merge this @davidfowl or should I just close? Don't want it clogging up my outstanding PR window any longer :p

**Comment by davidfowl** [comment]
Nooooooo! 😄

**Comment by shaggygi** [comment]
Appears the API link on page is broken.

**Comment by damieng** [comment]
Yes, the PR needed a question resolved and to be integrated with the build to actually generate the docs and subsequently be published on a github page...

**Pull request merged**
